# Generated by Django 2.1.3 on 2018-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181118_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
